In [2]:
import torch
torch.__version__

'2.0.0'

## Tensors

Tensors make up the fundamental blocks of ML. They represent data in a numerical manner. For example, RGB image of size $224\times 224$ would be described as a tensor of shape $[3, 224, 224]$, which means $[\text{colour\_channels}, \text{height}, \text{width}]$

### Creating Tensors:

#### Scalars:

In [3]:
# First we create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # Checking no. of dimensions

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

#### Vectors:

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim
# So "vector" is 1-dimensional which is expected

1

There is a trick to dimensionality: Number of dimensions in a tensor in PyTorch is the number of square brackets on the outside $([)$ and we only need to count one side

In [8]:
# Now, let's checkout the shape of "vector"
vector.shape
# This means that the vector has shape of [2] -> due to 2 elements, [7, 7]

torch.Size([2])

#### Matrices:

In [9]:
# Now, a matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape
# 1st dimension has shape 2 and 2nd dimension has shape 2

torch.Size([2, 2])

#### Tensors:

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape
# The dimensions go outer to inner
# Outer -> just has the whole thing
# 2nd -> the 3 rows
# 3 -> the elements of each row

torch.Size([1, 3, 3])

<p align="center">
  <img src="./images/tensor_dim.png" alt="tensor_dim" width="600" class="center"/>
</p>
<p align="center">
  This image illustrates which dimensions correspond to which part of the tensor
</p>

<p align="center">
  <img src="./images/svmt.png" alt="tensor_dim" width="600" class="center"/>
</p>
<p align="center">
  Scalars, Vectors, Matrices, Tensors
</p>

#### Random Tensors:

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.7417, 0.3238, 0.7123, 0.3543],
         [0.6309, 0.0743, 0.0789, 0.2398],
         [0.6785, 0.9550, 0.6369, 0.6539]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

For example, say you wanted a random tensor in the common image shape of $[224, 224, 3]$ $([\text{height}, \text{width}, \text{color\_channels}])$.

In [16]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Tensors with zeroes and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Creating range-based Tensors