In [1]:
import torch
torch.__version__

'2.0.0'

## Tensors

Tensors make up the fundamental blocks of ML. They represent data in a numerical manner. For example, RGB image of size $224\times 224$ would be described as a tensor of shape $[3, 224, 224]$, which means $[\text{colour\_channels}, \text{height}, \text{width}]$

### Creating Tensors:

#### Scalars:

In [2]:
# First we create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # Checking no. of dimensions

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

#### Vectors:

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim
# So "vector" is 1-dimensional which is expected

1

There is a trick to dimensionality: Number of dimensions in a tensor in PyTorch is the number of square brackets on the outside $([)$ and we only need to count one side

In [7]:
# Now, let's checkout the shape of "vector"
vector.shape
# This means that the vector has shape of [2] -> due to 2 elements, [7, 7]

torch.Size([2])

#### Matrices:

In [8]:
# Now, a matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape
# 1st dimension has shape 2 and 2nd dimension has shape 2

torch.Size([2, 2])

#### Tensors:

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape
# The dimensions go outer to inner
# Outer -> just has the whole thing
# 2nd -> the 3 rows
# 3 -> the elements of each row

torch.Size([1, 3, 3])

<p align="center">
  <img src="./images/tensor_dim.png" alt="tensor_dim" width="600" class="center"/>
</p>
<p align="center">
  This image illustrates which dimensions correspond to which part of the tensor
</p>

<p align="center">
  <img src="./images/svmt.png" alt="tensor_dim" width="600" class="center"/>
</p>
<p align="center">
  Scalars, Vectors, Matrices, Tensors
</p>

#### Random Tensors:

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.4238, 0.1410, 0.9631, 0.3007],
         [0.6620, 0.6620, 0.4337, 0.6187],
         [0.8267, 0.2988, 0.0348, 0.2654]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

For example, say you wanted a random tensor in the common image shape of $[224, 224, 3]$ $([\text{height}, \text{width}, \text{color\_channels}])$.

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Tensors with zeroes and ones

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

Creating range-based Tensors

In [18]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Creating similarly-shaped tensors

In [19]:
# Can also create a tensor of ones similar to another tensor
ten_ones = torch.ones_like(input=zero_to_ten) # will have same shape
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Tensor Dataypes

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

##### Common Issues with Tensors:
- Most common issues are shape issues where tensor shapes don't match up
- Some issues may arise due to tensors being different datatypes, one in `torch.float32` and another `torch.float16`
- One tensor on CPU and one on GPU, PyTorch likes tensors to be on same device

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2727, 0.2269, 0.6235, 0.7031],
        [0.7811, 0.9616, 0.3820, 0.6173],
        [0.5927, 0.3392, 0.5133, 0.2661]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating Tensors:
Common operations:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

#### Addition, Multiplication and Subtraction

In [23]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply it by 10
tensor * 10, tensor
# tensor doesn't change unless reassigned

(tensor([10, 20, 30]), tensor([1, 2, 3]))

In [25]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [26]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [27]:
# Can also use torch functions like mul or multiply
torch.mul(tensor, 10), tensor

(tensor([10, 20, 30]), tensor([1, 2, 3]))

#### Element-wise Multiplication and Matrix Multiplication

In [28]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [29]:
torch.matmul(tensor, tensor), tensor @ tensor
# Both output the same but @ not recommended

(tensor(14), tensor(14))

In [30]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1e+03 µs


tensor(14)

In [31]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

#### Shape Error

In [32]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [33]:
# torch.matmul(tensor_A, tensor_B) # (this will error)

In [34]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [35]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [36]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Linear Layer

In [37]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible using manual seed
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 0.5457,  0.0621, -0.0792, -0.8999,  1.1652,  1.0614],
        [ 0.8659,  1.3893, -1.1715, -1.8639,  1.8255,  1.5549],
        [ 1.1862,  2.7165, -2.2639, -2.8280,  2.4858,  2.0484]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


#### Aggregation-like operations (min, max, mean, sum)

In [38]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [40]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

#### Positional min/max

In [41]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [42]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype
# default is torch.float32

torch.float32

In [43]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [44]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)