In [1]:
import torch
torch.__version__

'2.0.0'

## Tensors

Tensors make up the fundamental blocks of ML. They represent data in a numerical manner. For example, RGB image of size $224\times 224$ would be described as a tensor of shape $[3, 224, 224]$, which means $[\text{colour\_channels}, \text{height}, \text{width}]$

### Creating Tensors:

#### Scalars:

In [2]:
# First we create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim # Checking no. of dimensions

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

#### Vectors:

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim
# So "vector" is 1-dimensional which is expected

1

There is a trick to dimensionality: Number of dimensions in a tensor in PyTorch is the number of square brackets on the outside $([)$ and we only need to count one side

In [8]:
# Now, let's checkout the shape of "vector"
vector.shape
# This means that the vector has shape of [2] -> due to 2 elements, [7, 7]

torch.Size([2])

In [9]:
# Now, a matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape
# 1st dimension has shape 2 and 2nd dimension has shape 2

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape
# The dimensions go outer to inner
# Outer -> just has the whole thing
# 2nd -> the 3 rows
# 3 -> the elements of each row

torch.Size([1, 3, 3])

<p align="center">
  <img src="./images/tensor_dim.png" alt="tensor_dim" width="600" class="center"/>
</p>
<p align="center">
  This image illustrates which dimensions correspond to which part of the tensor
</p>

<p align="center">
  <img src="./images/svmt.png" alt="tensor_dim" width="600" class="center"/>
</p>
<p align="center">
  Scalars, Vectors, Matrices, Tensors
</p>